#!/bin/zsh

if [ -f `find /etc/cont-init.d/ -maxdepth 1 -type f | grep -v "01-useradd\|99-default"` ]
then 
    scriptArray=( `find /etc/cont-init.d/ -maxdepth 1 -type f | grep -v "01-useradd\|99-default"` )

    if ! [[ ${#scriptArray[@]} -eq 0 ]]
    then 

        echo "[script-init] Found ${#scriptArray} scripts. Executing:"

        for (( i = 1 ; i <= ${#scriptArray} ; i++ ))
        do 
            /bin/zsh ${scriptArray[${i}]}
        done
    fi
fi

if [ -f `find /etc/services.d/ -maxdepth 1 -type f` ]
then
    serviceArray=( `find /etc/services.d/ -maxdepth 1 -type f` )
    
    if ! [[ ${#serviceArray[@]} -eq 0 ]]
    then

        echo "[service-init] Found ${#serviceArray} services. Executing:"
        
        for (( i = 1 ; i <= ${#serviceArray} ; i++ ))
        do 
            serviceName=`basename ${serviceArray[${i}]}`
            mkdir /etc/services.d/custom-${serviceName}
            mv ${serviceArray[${i}]} /etc/services.d/custom-${serviceName}/run 
            chmod +x /etc/services.d/custom-${serviceName}/run
            echo "[service init] Set up ${serviceName}"

        done
    fi
fi